### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by kylejlin** [pigulla/json-strictify#32]
When I import `json-strictify`, I get the following runtime error:

```text
Error: Cannot find module 'tslib'
```

This is caused by `"importHelpers": true` in [`tsconfig.json`](https://github.com/pigulla/json-strictify/blob/develop/tsconfig.json#L8).

Enabling `importHelpers` instructs the TypeScript compiler to emit `require("tslib")` in the generated code. Since `tslib` is not listed as a dependency in `package.json`, this causes the above runtime error to be thrown.

To fix this, either disable `importHelpers`, or install `tslib`.

**Comment by kylejlin** [comment]
If you want to reproduce this error, you can go to [`json-strictify`'s RunKit page](https://npm.runkit.com/json-strictify) and press the "Run" button.

**Comment by pigulla** [comment]
Thanks for the PR!
